# Generated by Django 4.2.3 on 2023-07-20 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='account',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AddField(
            model_name='forms',
            name='age',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='forms',
            name='branch',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AddField(
            model_name='forms',
            name='dist',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AddField(
            model_name='forms',
            name='dob',
            field=models.DateField(default=True),
        ),
        migrations.AddField(
            model_name='forms',
            name='gender',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AddField(
            model_name='forms',
            name='mail',
            field=models.EmailField(default=True, max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='forms',
            name='material',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='forms',
            name='phn',
            field=models.IntegerField(default=True),
        ),
        migrations.AlterField(
            model_name='forms',
            name='name',
            field=models.CharField(default=True, max_length=250),
        ),
    ]
