# Generated by Django 4.2.3 on 2023-07-20 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0002_forms_account_forms_age_forms_branch_forms_dist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forms',
            name='dob',
            field=models.CharField(default=True, max_length=20),
        ),
    ]
