# Generated by Django 4.2.3 on 2023-07-20 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0003_alter_forms_dob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forms',
            old_name='account',
            new_name='acc',
        ),
    ]
