# Generated by Django 4.2.3 on 2023-07-20 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0004_rename_account_forms_acc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forms',
            old_name='name',
            new_name='uname',
        ),
    ]
