# Generated by Django 4.2.3 on 2023-07-20 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0005_rename_name_forms_uname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forms',
            name='acc',
            field=models.CharField(choices=[('S', 'savings'), ('C', 'current')], max_length=50),
        ),
        migrations.AlterField(
            model_name='forms',
            name='dist',
            field=models.CharField(choices=[('Alapuzha', 'Alapuzha'), ('Ernakulam', 'Ernakulam'), ('Idukki', 'Idukki'), ('Kottayam', 'Kottayam'), ('Kozhikode', 'Kozhikode'), ('Palakkad', 'Palakkad')], max_length=50),
        ),
        migrations.AlterField(
            model_name='forms',
            name='gender',
            field=models.CharField(choices=[('M', 'male'), ('F', 'female')], max_length=10),
        ),
    ]
