# Generated by Django 4.2.3 on 2023-07-20 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0006_alter_forms_acc_alter_forms_dist_alter_forms_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forms',
            name='dist',
            field=models.CharField(choices=[('Alapuzha', 'dist1'), ('Ernakulam', 'dist2'), ('Idukki', 'dist3'), ('Kottayam', 'dist4'), ('Kozhikode', 'dist5'), ('Palakkad', 'dist6')], max_length=50),
        ),
    ]
