# Generated by Django 4.2.3 on 2023-07-20 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0007_alter_forms_dist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forms',
            name='branch',
            field=models.CharField(choices=[('br1', 'Cherthala'), ('br2', 'Kuttanad'), ('br3', 'Pattanakkad'), ('br4', 'Aluva'), ('br5', 'Eloor'), ('br6', 'Paravur'), ('br7', 'Adimali'), ('br8', 'Kattappana'), ('br9', 'Munnar'), ('br10', 'Ettumanoor'), ('br11', 'Kumarakam'), ('br12', 'Vaikom')], max_length=50),
        ),
    ]
