# Generated by Django 4.2.3 on 2023-07-20 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0008_alter_forms_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forms',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='forms',
            name='dist',
        ),
    ]
